CONST = {
    // Map constants
    TILESIZE : 64,
    WALL_DAMAGE : 0.5,
    
    // Entity constants
    PLAYER_SIZE : 64,
    PLAYER_MAX_SPEED : 3,
    PLAYER_ACCELERATION : 0.3,
    PLAYER_DRAG : 0.1,
    PLAYER_HEALTH : 100,
    PLAYER_HITBOX_SIZE : 45,
    PLAYER_START_GOLD : 10,

    CANNON_SPEED_FACTOR : 3,
    CANNON_VISION_FACTOR : 5,
    CANNON_START_ANGLE : Math.PI/3,
    CANNONBALL_DIAMETER : 8,
    CANNONBALL_DAMAGE : 10,


    TURRET_FIRING_RANGE : 7,
    TURRET_FRAME_FREQ : 100,
    TURRET_HEALTH : 50,
    TURRET_SIZE : 16,
    TURRET_REPAIR_TIME : 500,

    // Bot constants
    BOT_LOW_HEALTH : 50,

    // Mechanics constants
    HEARTBEAT_INTERVAL : 50,
    INVINCIBILITY_FRAMES : 200,
    TREASURE_FISH_TIME : 125,
    GOLD_AMT : 10,

    SIDE_DAMAGE_MULTIPLIER : 1,
    FRONT_BACK_DAMAGE_MULTIPLIER : 0.25,

    UPDATE_ESCAPEPIVOTS : 150,
}

CONST['RANGESTAT'] = {
    a        :1.2/0.7,
    b        :0.9/0.7,
    framelife:18, // 
    range    :CONST.PLAYER_SIZE*CONST.CANNON_VISION_FACTOR
}


module.exports = {
    CONST: CONST    
}
