module.exports = {
  name: function () {
    const rank = [
      "",
      "",
      "",
      "Pirate",
      "Captain",
      "Cap'n",
      "Admiral",
      "Firstmate",
      "Gunner",
      "Powdermonkey",
      "Boatswain",
      "Old",
      "Sailor",
      "Lt",
      "Lord",
      "Little",
      "Sir",
      "Big",
      "Jolly",
      "Great",
      "Crewmate",
      "Dirty",
    ];

    const firstName = [
      "Pirate",
      "Grape",
      "Red",
      "Gold",
      "Silver",
      "o'",
      "Wet",
      "Sea",
      "River",
      "Ocean",
      "Lake",
      "Mitchell",
      "Arkie",
      "Sean",
      "Prem",
      "Davey",
      "Jack",
      "Peeko",
      "Grim",
      "Skull",
      "Scurvy",
      "Roger",
      "Crab",
      "Spike",
      "Dagger",
      "Hook",
      "Song",
      "Barnacle",
      "Starfish",
      "Oyster",
    ]
    const lastName = [
      "",
      "",
      "",
      " Pirate",
      "-Beard",
      " ol'Dog",
      "-Leg",
      "-Foot",
      "-Eye",
      "-Face",
      "-Claw",
      " the Great",
      " the Terrible",
      " the Sick",
      " the Feared",
      " of the Sea",
      " McPirate",
      " McNugget",
      " Knives",
      " Sparrow",
      " Whatsisname",
      " Fang",
      " Matey",
      " Scallywag",
      " Booty",
    ]

    var selectedRank = rank[Math.floor(Math.random() * rank.length)]
    var selectedFirstName = firstName[Math.floor(Math.random() * firstName.length)]
    var selectedLastName = lastName[Math.floor(Math.random() * lastName.length)]

    return selectedRank + " " + selectedFirstName + selectedLastName
  }
}
